version: 1.2
workflows:
  - name: 'PRSmix'
    subclass: WDL
    primaryDescriptorPath: /PRSmix.wdl
    readMePath: /README.md
    testParameterFiles:
      - /PRSmix.json
    authors:
        - name: Buu Truong 
          email: btruong@broadinstitute.org