version: 1.2
workflows:
  - name: 'PRSmix'
    subclass: WDL
    primaryDescriptorPath: /PRSmix.wdl
    readMePath: /README.md
    doi: doi.org/10.1016/j.xgen.2024.100523
    testParameterFiles:
      - /PRSmix.json
    authors:
        - name: Buu Truong 
          email: btruong@broadinstitute.org